flat_first.Rmd:
  path: dev/flat_first.Rmd
  state: active
  R:
  - R/cargo_add.R
  - R/cargo_build.R
  - R/cargo_check.R
  - R/cargo_doc.R
  - R/cargo_new.R
  - R/cargo_run.R
  - R/cargo_test.R
  - R/install_cargo.R
  - R/rust_install.R
  - R/rust_uninstall.R
  - R/rust_update.R
  - R/rustc_rs.R
  - R/uninstall_cargo.R
  tests:
  - tests/testthat/test-rust_install.R
  - tests/testthat/test-rust_update.R
  - tests/testthat/test-rust_uninstall.R
  - tests/testthat/test-rustc_rs.R
  - tests/testthat/test-cargo_new.R
  - tests/testthat/test-cargo_build.R
  - tests/testthat/test-cargo_run.R
  - tests/testthat/test-cargo_check.R
  - tests/testthat/test-cargo_test.R
  - tests/testthat/test-install_cargo.R
  - tests/testthat/test-uninstall_cargo.R
  - tests/testthat/test-cargo_doc.R
  - tests/testthat/test-cargo_add.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_first.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
