# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' cargo_add
#' 
#' the "cargo add " command
#' @param project chr the project names with dirs
#' @param package chr the package need to used
#' @param additional chr additional parameters in build 
#' @return web
#' 
#' @export 
cargo_add <- function(package,project = ".",additional = NULL){
   message(glue::glue("you are now building rust project in {project}"))
  
  dir_check <- dir.exists(project)
  if (!dir_check){
    stop("the project dir does not exist")
  }
  for(i in package){
    if (!is.null(additional)) {
   commandline <- glue::glue("cd {project} && cargo add {i} {additional}")
  } else {
    commandline <- glue::glue("cd {project} && cargo add {i}")
  }
  system(command = commandline)
  }
  return(project)
    
}
