# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' cargo_check
#' 
#' the "cargo check "command
#' @param project chr the project names with dirs
#' @param additional chr additional parameters in build 
#'
#' @return project
#'
#' @export
#' @examples
#' cargo_check("dev/hello_world")
cargo_check <- function(project,additional = NULL){
   message(glue::glue("you are now building rust project in {project}"))
  
  dir_check <- dir.exists(project)
  
  if (!dir_check){
    stop("the project dir does not exist")
  }
  
  if (!is.null(additional)) {
   commandline <- glue::glue("cd {project} && cargo check {additional}")
  }else {
    commandline <- glue::glue("cd {project} && cargo check")
  }
  system(command = commandline)
  return(project)
    
}
