# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' cargo_new
#' 
#' the "cargo new" command
#' @param project chr the project names with dirs
#' @param lib chr the "--lib" parameter 
#' @param root chr the root dir of project,default as "."
#' 
#' @return project
#' 
#' @export
#' @examples
#' hello_world <- cargo_new("dev/hello_world")
cargo_new <- function(project,lib = FALSE,root = "."){
  
  message(glue::glue("you are now creating rust project in {getwd()}"))
  if (!lib){
    lib <- "--lib"
  }else {
    lib <- ""
  }
  dir_check <- dir.exists(root)
  
  if (!dir_check){
    stop("the root dir does not exist")
  }
  
  if (root == "."){
    project <- project
  } else {
    project <- glue::glue("{root}/{project}")
  }
  message(glue::glue("creating application as {project}"))
  commandline <- glue::glue("cargo new {project} {lib}")
  system(command = commandline)
  return(project)
}
