# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' install_cargo
#' 
#' the "cargo install "command
#' @param project chr the package names
#' @param additional chr additional parameters in build 
#'
#' @return null
#'
#' @export
install_cargo <- function(project,additional = NULL){
   message(glue::glue("you are now building rust project in {project}"))
  for (i in project){
  if (!is.null(additional)) {
   commandline <- glue::glue("cargo install {i} {additional}")
  }else {
    commandline <- glue::glue("cargo install {i}")
  }
  system(command = commandline)
  }
  return(project)
    
}
