# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' rust_uninstall
#' 
#' uninstall rust in linux and macos
#' 
#' @return null
#' 
#' @export
rust_uninstall <- function(){
    system(command = "rustup self uninstall")
}
