# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' rustc_rs
#' 
#' compile a single rs file by rustc
#' @param rsfile chr a rs file in its dir
#' @return rsfile
#' 
#' @export
rustc_rs <- function(rsfile){
  if (file.exist(rsfile)){
    system(command = glue::glue("rustc {rsfile}"))
  } else {
    stop("check your files dir")
  }
  return(rsfile)
}
