# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' rust_install
#' 
#' install rust in linux and macos
#' 
#' @return null
#' 
#' @export
#' @examples
#' rust_install()
rust_install <- function(){
    system(command = "curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
")
}
