# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' rust_update
#' 
#' update rust in linux and macos
#' 
#' @return null
#' 
#' @export
rust_update <- function(){
    system(command = "rustup update")
}
