# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' typst_install
#' 
#' install typst in cargo
#' 
#'
#' @return null
#'
#' @export
typst_install <- function(){
   install_cargo("--git https://github.com/typst/typst --locked typst-cli")
}
